{
 "title": "Monerod",
 "description": "Metrics of your monero full node",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Sync progress",
   "type": "stat",
   "description": "Displays the progress of the sync.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monerod_sync_percentage", "legendFormat": "Progress" }
   ]
  },
  {
   "title": "Update available",
   "type": "stat",
   "description": "Displays if an update is available.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monerod_update_available" }
   ]
  },
  {
   "title": "Block height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "monerod_height", "legendFormat": "Block height" }
   ]
  },
  {
   "title": "Mining status",
   "type": "stat",
   "description": "Displays if full node is mining or not.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monerod_is_mining_active" }
   ]
  },
  {
   "title": "Mining threads",
   "type": "stat",
   "description": "Number of mining threads",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monerod_mining_threads", "legendFormat": "Threads" }
   ]
  },
  {
   "title": "Block Difficulty",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "monerod_block_difficulty", "legendFormat": "Difficulty" }
   ]
  },
  {
   "title": "Mempool",
   "type": "timeseries",
   "description": "Displays how much transactions are in the mempool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "monerod_tx_mempool", "legendFormat": "Txs" }
   ]
  },
  {
   "title": "Tx chain",
   "type": "timeseries",
   "description": "Number of transactions on the blockchain",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "monerod_tx_chain", "legendFormat": "Txs" }
   ]
  },
  {
   "title": "Blockchain size",
   "type": "timeseries",
   "description": "Size of the blockchain in GB (SI)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "monerod_database_size", "legendFormat": "Blockchain size" }
   ]
  },
  {
   "title": "Banned peers",
   "type": "timeseries",
   "description": "Number of  banned peers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "monerod_peer_bans", "legendFormat": "Banned peers" }
   ]
  },
  {
   "title": "Block reward",
   "type": "timeseries",
   "description": "Coinbase transaction per block",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "XMR" } },
   "targets": [
    { "expr": "monerod_block_reward", "legendFormat": "Block reward" }
   ]
  },
  {
   "title": "Outgoing connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "monerod_connections_outgoing", "legendFormat": "Outgoing connections" }
   ]
  },
  {
   "title": "Incoming connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "monerod_connections_incoming", "legendFormat": "Incoming connections" }
   ]
  },
  {
   "title": "Mining Hashrate",
   "type": "timeseries",
   "description": "Hashrate of mining process on your full node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "targets": [
    { "expr": "monerod_mining_speed", "legendFormat": "Hashrate" }
   ]
  }
 ]
}